name: Update Quartz Framework

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly on Sunday midnight
  workflow_dispatch:    # Allow manual run

jobs:
  update-quartz:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Add Quartz upstream
      run: |
        git remote add upstream https://github.com/jackyzha0/quartz.git
        git fetch upstream

    - name: Update upstream-v4 branch
      run: |
        git
